### ISSUE TITLE
Sprint #4: Dokumentation

### ISSUE THREAD

**Issue by kps85** [kps85/PPSN#107]
**DOKUMENTATION:**
- _Funktionsweise aufschreiben:_
  - #98 Suche  **√**
  -  #99 Folgen **√**
  -  #100 Nachricht ausblenden **√**
  -  #101 User ausblenden **√**
  -  #102 Nachrichten addressieren **√**
  -  #103 Gruppe erstellen **√**
  -  #104 Gruppenseite **√**
  -  #105 Gruppe bearbeiten **√**
- _Datenobjekte notieren:_
  - #98 Suche  **√**
  -  #99 Folgen **√**
  -  #100 Nachricht ausblenden **√**
  -  #101 User ausblenden **√**
  -  #102 Nachrichten addressieren **√**
  -  #103 Gruppe erstellen **√**
  -  #104 Gruppenseite **√**
  -  #105 Gruppe bearbeiten **√**
- _Texte der Infoseite hinzufügen:_  
  - #98 Suche  **√**
  -  #99 Folgen **√**
  -  #100 Nachricht ausblenden **√**
  -  #101 User ausblenden **√**
  -  #102 Nachrichten addressieren **√**
  -  #103 Gruppe erstellen **√**
  -  #104 Gruppenseite **√**
  -  #105 Gruppe bearbeiten **√**
- _Use-Case-Diagramm erstellen:_
  - #98 Suche  **√**
  -  #99 Folgen **√**
  -  #100 Nachricht ausblenden **√**
  -  #101 User ausblenden **√**
  -  #102 Nachrichten addressieren **√**
  -  #103 Gruppe erstellen **√**
  -  #105 Gruppe bearbeiten **√**
- _EER-Diagramm ggf. erweitern:_
  -  #99 Folgen **√**
  -  #100 Nachricht ausblenden **√**
  -  #101 User ausblenden **√**
  -  #102 Nachrichten addressieren **√**
  - #103 Gruppe erstellen **√**
  - #105 Gruppe bearbeiten **√**

**Comment by Tomelinho** [comment]
**Dokumentation**

- EER-Diagramm ggf. erweitern

**Comment by Tomelinho** [comment]
**DONE:**
- _Funktionsweise aufschreiben:_
  - #98 Suche 
  -  #99 Folgen
  -  #100 Nachricht ausblenden
  -  #101 User ausblenden
  -  #102 Nachrichten addressieren
  -  #103 Gruppe erstellen
  -  #104 Gruppenseite
  -  #105 Gruppe bearbeiten
- _Datenobjekte notieren:_
  - #98 Suche 
  -  #99 Folgen
  -  #100 Nachricht ausblenden
  -  #101 User ausblenden
  -  #102 Nachrichten addressieren
  -  #103 Gruppe erstellen
  -  #104 Gruppenseite
  -  #105 Gruppe bearbeiten
- _Texte der Infoseite hinzufügen:_  
  - #98 Suche 
  -  #99 Folgen
  -  #100 Nachricht ausblenden
  -  #101 User ausblenden
  -  #102 Nachrichten addressieren
  -  #103 Gruppe erstellen
  -  #104 Gruppenseite
  -  #105 Gruppe bearbeiten
- _Use-Case-Diagramm erstellen:_
  - #98 Suche 
  -  #99 Folgen
  -  #100 Nachricht ausblenden
  -  #101 User ausblenden
  -  #102 Nachrichten addressieren
  -  #103 Gruppe erstellen
  -  #105 Gruppe bearbeiten

**Comment by kps85** [comment]
**DONE**
- _EER-Diagramm ggf. erweitern:_
  -  #99 Folgen
  -  #100 Nachricht ausblenden
  -  #101 User ausblenden
  -  #102 Nachrichten addressieren
  - #103 Gruppe erstellen
  - #105 Gruppe bearbeiten
