### ISSUE TITLE
TwitTUr soll dem Benutzer ermöglichen, sich über ein Formular zu registrieren.

### ISSUE THREAD

**Issue by kps85** [kps85/PPSN#60]
**TASKS**:
- _Frontend_:
  - notwendige GUI-Elemente hinzufügen
- _Backend_:
  - entsprechende Queries implementieren
  - entsprechende Funktionen für die GUI-Elemente implementieren
- _Dokumentation_:
  - Dokumentation fortführen und entsprechende Einträge für die Hilfe-Seiten erstellen
- _Tests_:
  - Funktionen und Queries testen

**Comment by ghost** [comment]
Registrierung funktioniert, aber Exeptions noch nicht implementiert.
