### ISSUE TITLE
TwitTUr soll dem Benutzer ermöglichen, sich über ein Formular einzuloggen.

### ISSUE THREAD

**Issue by kps85** [kps85/PPSN#61]
**TASKS**:
- _Frontend_:
  - notwendige GUI-Elemente hinzufügen
- _Backend_:
  - entsprechende Queries implementieren
  - entsprechende Funktionen für die GUI-Elemente implementieren
- _Dokumentation_:
  - Dokumentation fortführen und entsprechende Einträge für die Hilfe-Seiten erstellen
- _Tests_:
  - Funktionen und Queries testen

**Comment by ghost** [comment]
Test:
Falls Login erfolgreich war, so wird man auf die Profilseite des Benutzers weitergeleitet.
Falls nicht, wird man auf die Logikseite zurückgeleitet.
