### ISSUE TITLE
allgemeine GUI zur Verwendung der Plattform

### ISSUE THREAD

**Issue by kps85** [kps85/PPSN#84]
**TASKS**:
- _Frontend_:
  - Navigation einbauen **√**
  - Links für Start-, Profil-, Info-, Einstellungsseite **√**
  - twittur Logo zur Identifikation des Systems implementieren **√**
  - Widget-Sidebar für Untermenüs der einzelnen Seiten anbieten **√**
  - CSS für GUI design **√**
  - JS functions für weitere Funktionalität **√**
- _Backend_:
  - urls, namespace und co einrichten **√**
- _Dokumentation_:
  - Funktionsweise aufschreiben **√**
  - Datenobjekte notieren **√**
  - Use-Case-Diagramm erstellen **√**
- _Tests_:
  - mittels URLs und Links durch die Seite navigieren **√**
  - twittur wird mit einer GUI dargestellt. **√**

**Comment by kps85** [comment]
**DONE**:
- _Frontend_
  - Button zum Erstellen einer neuen Nachricht
  - Links für Start-, Profil-, Info-, Einstellungsseite
  - twittur Logo zur Identifikation des Systems implementieren
- _Tests_
  - Mittels URLs und Links durch die Seite navigieren
  - Twittur wird mit einer GUI dargestellt.

**Comment by kps85** [comment]
**DONE**:
- _Frontend_:
  - Navigation einbauen
  - Widget-Sidebar für Untermenüs der einzelnen Seiten anbieten
  - CSS für GUI design
  - JS functions für weitere Funktionalität
- _Backend_:
  - urls, namespace und co einrichten

**Comment by Tomelinho** [comment]
**DONE:**
- _Dokumentation:_
  - Funktionsweise aufschreiben
  - Datenobjekte notieren
  - Use-Case-Diagramm erstellen

**UPDATE:**
- _Dokumentation:_
  - "relevante Texte der Infoseite hinzufügen" entfernt, da bereits vorhanden
  - "EER-Diagramm ggf. erweitern" entfernt
