### ISSUE TITLE
Account anlegen

### ISSUE THREAD

**Issue by kps85** [kps85/PPSN#85]
**TASKS**:
- _Frontend_:
  - register box auf FTU **√**
  - input fields für username, password, first_name, last_name, e-mail, studiengang **√**
  - submit und reset buttons **√**
  - CSS für GUI design **√**
  - JS functions für weitere Funktionalität **√**
- _Backend_:
  - Funktionen zum Anlegen des Users implementieren **√**
  - entsprechende View um notwendige Elemente erweitern **√**
- _Dokumentation_:
  - Funktionsweise aufschreiben **√**
  - Datenobjekte notieren **√**
  - relevante Texte der Infoseite hinzufügen **√**
  - Use-Case-Diagramm erstellen **√**
- _Tests_:
  - neuen Testnutzer anlegen **√**
  - Nach dem Registrationsvorgang ist ein Benutzer in der Datenbank korrekt erfasst. **√**

**Comment by ghost** [comment]
_DONE_
- _Frontend_:
  - register box auf FTU
  - input fields für username, password, first_name, last_name, e-mail, studiengang
  - submit und reset buttons
  - CSS für GUI design
  - JS functions für weitere Funktionalität
- _Backend_:
  - Funktionen zum Anlegen des Users implementieren
  - entsprechende View um notwendige Elemente erweitern
- _Dokumentation_:
  - Funktionsweise aufschreiben
- _Tests_:
  - neuen Testnutzer anlegen
  - Nach dem Registrationsvorgang ist ein Benutzer in der Datenbank korrekt erfasst.

**Comment by Tomelinho** [comment]
**DONE:**
-  _Dokumentation:_
  - Datenobjekte notieren
  - relevante Texte der Infoseite hinzufügen
  - Use-Case-Diagramm erstellen

**UPDATE:**
-  _Dokumentation:_
  - "EER-Diagramm ggf. erweitern" entfernt
