### ISSUE TITLE
Account verwalten

### ISSUE THREAD

**Issue by kps85** [kps85/PPSN#86]
**TASKS**:
- _Frontend_:
  - Login Box auf FTU **√**
  - Inputs für username, password **√**
  - login button **√**
  - logout button auf Seite implementieren **√**
  - delete Account button auf Einstellungsseite implementieren **√**
  - CSS für GUI design **√**
  - JS functions für weitere Funktionalität **√**
- _Backend_:
  - Funktion zur Verwaltung der user-session implementieren **√**
  - Funktion zum Löschen des User-Accounts anlegen **√**
  - entsprechende Views um notwendige Elemente erweitern **√**
  - extend FTU view  **√**
  - extend settings view **√**
- _Dokumentation_:
  - Funktionsweise aufschreiben **√**
  - Datenobjekte notieren **√**
  - relevante Texte der Infoseite hinzufügen **√**
  - Use-Case-Diagramm erstellen **√**
- _Tests_:
  - testuser einloggen **√**
  - testuser ausloggen **√**
  - testuser account löschen **√**
  - Der Benutzer kann über die Accountverwaltung seinen Account verwalten. **√**

**Comment by kps85** [comment]
**DONE**
- _Frontend_
  - logout button auf Seite implementieren
  - delete Account button auf Einstellungsseite implementieren
- _Backend_
  - Funktion zur Verwaltung der user-session implementieren
  - Funktion zum Löschen des User-Accounts anlegen
  - extend settings view
- _Tests_
  - Testuser einloggen
  - Testuser ausloggen
  - Testuser account löschen
  - Der Benutzer kann über die Accountverwaltung seinen Account verwalten.

**UPDATE**
- _Backend_
  - "Funktion zum Beenden der user-session implementieren" entfernt, Duplikat

**Comment by kps85** [comment]
**DONE**:
- _Frontend_:
  - Login Box auf FTU
  - Inputs für username, password
  - login button
  - CSS für GUI design
  - JS functions für weitere Funktionalität
- _Backend_:
  - entsprechende Views um notwendige Elemente erweitern
  - extend FTU view

**Comment by Tomelinho** [comment]
**DONE:**
- _Dokumentation:_
  - Funktionsweise aufschreiben
  - Datenobjekte notieren
  - Relevante Texte der Infoseite hinzufügen
  - Use-Case-Diagramm erstellen

**UPDATE:**
- _Dokumentation:_
  - "EER-Diagramm ggf. erweitern" entfernt
