### ISSUE TITLE
Passwort zurücksetzen bzw. ändern

### ISSUE THREAD

**Issue by kps85** [kps85/PPSN#87]
**TASKS**:
- _Frontend_:
  - PW reset box auf FTU  **√**
  - Input fields auf Einstellungs-Seite **√**
  - CSS für GUI design **√**
  - JS functions für weitere Funktionalität **√**
- _Backend_:
  - Funktion zum updaten der user zeile hinzufügen **√**
  - entsprechende View um notwendige Elemente erweitern **√**
- _Dokumentation_:
  - siehe #113
- _Tests_:
  - Passwort-Reset auf Testuser anwenden **√**
  - Das Passwort wurde erfolgreich geändert bzw. zurückgesetzt. **√**

**Comment by kps85** [comment]
**DONE**
- _Frontend_
  - Input fields auf Einstellungs-Seite
- _Backend_
  - funktion zum updaten der user zeile hinzufügen
  - entsprechende View um notwendige Elemente erweitern (settings page)

**UPDATE**
- _Backend_
  - "password spalte in user tabelle hinzufügen" entfernt, unnötig
- _Tests_
  - Passwort-Reset auf Testuser anwenden
  - Das Passwort wurde erfolgreich geändert bzw. zurückgesetzt.

**Comment by Tomelinho** [comment]
**DONE:**

-  *Dokumentation:*

 - Funktionsweise aufschreiben
 - Datenobjekte notieren
 - relevante Texte der Infoseite hinzufügen
 - Use-Case-Diagramm erstellen

**UPDATE:**

-  *Dokumentation:*

 - "EER-Diagramm ggf. erweitern" entfernt, da es nicht notwendig ist

**Comment by kps85** [comment]
**DONE**:
- _Frontend_:
  - PW reset box auf FTU
  - CSS für GUI design
  - JS functions für weitere Funktionalität
- _Backend_:
  - entsprechende View um notwendige Elemente erweitern
- _Tests_:
  - Passwort-Reset auf Testuser anwenden
  - Das Passwort wurde erfolgreich geändert bzw. zurückgesetzt.
