### ISSUE TITLE
Nachricht schreiben und verwalten

### ISSUE THREAD

**Issue by kps85** [kps85/PPSN#88]
**TASKS**:
- _Frontend_:
  - 'Create Message' Box auf relevanten Seiten implementieren (Startseite, Profilseite) **√**
  - input für Nachricht **√**
  - submit button implementieren **√**
  - GUI Elemente zum bearbeiten und löschen der Nachrichten dem Nachrichten  Block hinzufügen **√**
  - CSS für GUI design **√**
  - JS functions für weitere Funktionalität **√**
- _Backend_:
  - Funktionen zum Eintragen der Nachrichten in die DB implementieren **√**
  - Funktionen zum updaten und löschen einer Nachricht **√**
  - entsprechende Views um notwendige Elemente erweitern **√**
- _Dokumentation_:
  - Funktionsweise aufschreiben **√**
  - Datenobjekte notieren **√**
  - relevante Texte der Infoseite hinzufügen **√**
  - Use-Case-Diagramm erstellen **√**
- _Tests_:
  - Nachricht schreiben und im Anschluß bearbeiten und löschen **√**

**Comment by kps85** [comment]
**DONE**
- _Frontend_
  - 'Create Message' Box auf relevanten Seiten implementieren (Startseite, Profilseite, ?)
  - input für Nachricht
  - submit button implementieren
- _Backend_
  - Funktionen zum Eintragen der Nachrichten in die DB implementieren
  - entsprechende Views um notwendige Elemente erweitern

**UPDATE**
- _Backend_
  - "Datenbank um relevante Spalten und Tabellen erweitern" entfernt, nicht für diesen Sprint geeignet, relevante Spalten bereits vorhanden

**Comment by kps85** [comment]
**DONE**:
- _Frontend_:
  - GUI Elemente zum bearbeiten und löschen der Nachrichten dem Nachrichten Block hinzufügen
  - CSS für GUI design
  - JS functions für weitere Funktionalität
- _Backend_:
  - Funktionen zum updaten und löschen einer Nachricht
- _Tests_:
  - Nachricht schreiben und im Anschluß bearbeiten und löschen

**UPDATE**:
- _Backend_:
  - Funktionen zum updaten und löschen einer Nachricht
- _Tests_:
  - "Benutzer können anderen Benutzern Nachrichten schreiben." entfernt, nicht Bestandteil des Sprints!

**Comment by Tomelinho** [comment]
**DONE:**
- _Dokumentation:_
  - Funktionsweise aufschreiben
  - Datenobjekte notieren
  - Relevante Texte der Infoseite hinzufügen
  - Use-Case-Diagramm erstellen

**UPDATE:**
- _Dokumentation:_
  - "EER-Diagramm ggf. erweitern" entfernt
