### ISSUE TITLE
Nachrichten einsehen

### ISSUE THREAD

**Issue by kps85** [kps85/PPSN#89]
**TASKS**:
- _Frontend_:
  - Nachrichten Block auf relevanten Seiten implementieren **√**
  - GUI Elemente für Absender, Nachricht, Datum **√**
  - auf: FTU, Startseite, Profilseite **√**
  - CSS für GUI design **√**
  - JS functions für weitere Funktionalität **√**
- _Backend_:
  - Funktionen zum Auslesen der Nachrichten aus der DB implementieren **√**
  - entsprechende Views um notwendige Elemente erweitern **√**
- _Dokumentation_:
  - Funktionsweise aufschreiben **√**
  - Datenobjekte notieren **√**
  - relevante Texte der Infoseite hinzufügen **√**
  - Use-Case-Diagramm erstellen **√**
- _Tests_:
  - Nachricht schreiben und auf den entsprechenden Seiten anzeigen lassen **√**
  - Benutzern werden Nachrichten angezeigt. **√**

**Comment by liliabut** [comment]
**DONE**:
- _Tests_:
  - Nachricht schreiben und auf den entsprechenden Seiten anzeigen lassen
  - Benutzern werden Nachrichten angezeigt

**Comment by kps85** [comment]
**DONE**:
- _Frontend_:
  - Nachrichten Block auf relevanten Seiten implementieren
  - GUI Elemente für Absender, Nachricht, Datum
  - auf: FTU, Startseite, Profilseite
  - CSS für GUI design
  - JS functions für weitere Funktionalität
- _Backend_:
  - Funktionen zum Auslesen der Nachrichten aus der DB implementieren
  - entsprechende Views um notwendige Elemente erweitern

**Comment by Tomelinho** [comment]
**DONE:**
- _Dokumentation:_
  - Funktionsweise aufschreiben
  - Datenobjekte notieren
  - relevante Texte der Infoseite hinzufügen
  -  Use-Case-Diagramm erstellen

**UPDATE:**
- _Dokumentation:_
  - "EER-Diagramm ggf. erweitern" entfernt
