### ISSUE TITLE
Startseite zum informieren für Gäste (First-Time-Use-Seite)

### ISSUE THREAD

**Issue by kps85** [kps85/PPSN#90]
**TASKS**:
- _Frontend_:
  - Es muss eine First-Time-Use-Seite angelegt werden **√**
  - Die Funktionen von twittur müssen auf der Seite ersichtlich sein **√**
  - CSS für GUI Design **√**
  - JS functions für weitere Funktionalität **√**
- _Backend_:
  - Einen View erstellen, der das Frondendtemplate mit dem Modelobject verbindet **√**
- _Dokumentation_:
  - Funktionsweise aufschreiben **√**
  - Datenobjekte notieren **√**
  - relevante Texte der Infoseite hinzufügen **√**
  - Use-Case-Diagramm erstellen **√**
- _Tests_:
  - Testen ob die Funktionen korrekt angezeit werden **√**
  - Es existiert eine Startseite, auf der sich der Gast über twittur informieren kann. **√**

**Comment by ghost** [comment]
**DONE**:
- _Frontend_:
  - Es muss eine First-Time-Use-Seite angelegt werden
  - Die Funktionen von twittur müssen auf der Seite ersichtlich sein
  - CSS für GUI Design
  - JS functions für weitere Funktionalität
- _Backend_:
  - Einen View erstellen, der das Frondendtemplate mit dem Modelobject verbindet
- _Tests_:
  - Testen ob die Funktionen korrekt angezeit werden
  - Es existiert eine Startseite, auf der sich der Gast über twittur informieren kann.

**Comment by Tomelinho** [comment]
**DONE:** 
- _Dokumentation:_
  - Funktionsweise aufschreiben
  - Datenobjekte notieren
  - relevante Texte der Infoseite hinzufügen
  - Use-Case-Diagramm erstellen

**UPDATE:** 
-  _Dokumentation:_
  - "EER-Diagramm ggf. erweitern" entfernt
