### ISSUE TITLE
Startseite zum anmelden und registrieren für Gäste (First-Time-Use-Seite)

### ISSUE THREAD

**Issue by kps85** [kps85/PPSN#91]
**TASKS**:
- _Frontend_:
  - Es muss eine First-Time-Use-Seite angelegt werden **√**
  - Es muss ein Text-inputfeld für den Usernamen und ein Passwort-inputfield sowie ein Submitbutton für die Anmeldung erstellt werden **√**
  - Es muss ein Text-inputfeld für den Name, den Usernamen, die E-mailadresse und ein Passwort-inputfield sowie ein Submitbutton für die Registrierung erstellt werden **√**
  - Wenn der Benutzer auf Passwort vergessen klickt, muss ein Formular mit Text-inputfeldern für den Benutzernamen und die E-Mailadresse erscheinen **√**
  - CSS für GUI Design **√**
  - JS functions für weitere Funktionalität **√**
- _Backend_:
  - Die Registrierungsdaten müssen an die Datenbank geschickt werden und der User muss angelegt werden **√**
  - Wenn der User die korrekten Daten eingibt, muss er eingeloggt werden und auf die Startseite weitergeleitet werden **√**
  - Einen View erstellen, der das Frondendtemplate mit dem Modelobject verbindet **√**
- _Dokumentation_:
  - Funktionsweise aufschreiben **√**
  - Datenobjekte notieren **√**
  - relevante Texte der Infoseite hinzufügen **√**
  - Use-Case-Diagramm erstellen **√**
- _Tests_:
  - Seite aufrufen, alle Verlinkungen testen **√**
  - Datenbankeinträge kontrollieren, User anlegen und einloggen **√**
  - Es existiert eine Startseite, auf der sich ein Benutzer registrieren und anmelden kann. **√**

**Comment by ghost** [comment]
_DONE_
- _Backend_:
  - Die Registrierungsdaten müssen an die Datenbank geschickt werden und der User muss angelegt werden
  - Wenn der User die korrekten Daten eingibt, muss er eingeloggt werden und auf die Startseite weitergeleitet werden
  - Einen View erstellen, der das Frondendtemplate mit dem Modelobject verbindet
- _Dokumentation_:
  - Funktionsweise aufschreiben
- _Tests_:
  - Seite aufrufen, alle Verlinkungen testen
  - Datenbankeinträge kontrollieren, User anlegen und einloggen
  - Es existiert eine Startseite, auf der sich ein Benutzer registrieren und anmelden kann.

**Comment by kps85** [comment]
**DONE**:
- _Frontend_:
  - Es muss eine First-Time-Use-Seite angelegt werden
  - Es muss ein Text-inputfeld für den Usernamen und ein Passwort-inputfield sowie ein Submitbutton für die Anmeldung erstellt werden
  - Es muss ein Text-inputfeld für den Name, den Usernamen, die E-mailadresse und ein Passwort-inputfield sowie ein Submitbutton für die Registrierung erstellt werden
  - Wenn der Benutzer auf Passwort vergessen klickt, muss ein Formular mit Text-inputfeldern für den Benutzernamen und die E-Mailadresse erscheinen
  - CSS für GUI Design
  - JS functions für weitere Funktionalität
- _Tests_:
  - Seite aufrufen, alle Verlinkungen testen
  - Datenbankeinträge kontrollieren, User anlegen und einloggen
  - Es existiert eine Startseite, auf der sich ein Benutzer registrieren und anmelden kann.

**Comment by Tomelinho** [comment]
**DONE:** 
- _Dokumentation:_
  - Datenobjekte notieren
  - relevante Texte der Infoseite hinzufügen
  - Use-Case-Diagramm erstellen

**UPDATE:** 
- _Dokumentation:_
  - "EER-Diagramm ggf. erweitern" entfernt

**Comment by kps85** [comment]
**DONE**
- _Dokumentation_
  - Funktionsweise aufschreiben
