### ISSUE TITLE
separate Startseite für eingeloggte Benutzer (Startseite)

### ISSUE THREAD

**Issue by kps85** [kps85/PPSN#92]
**TASKS**:
- _Frontend_:
  - Es muss eine Startseite angelegt werden **√**
  - CSS für GUI Design **√**
  - JS functions für weitere Funktionalität **√**
  - Platz zur Anzeige von Nachrichten **√**
- _Backend_:
  - Einen View erstellen, der das Fronendtemplate mit dem Modelobject verbindet **√**
  - Den View um entsprechende Funktionen zur Anzeige von Nachrichten erweitern **√**
- _Dokumentation_:
  - Funktionsweise aufschreiben **√**
  - Datenobjekte notieren **√**
  - relevante Texte der Infoseite hinzufügen **√**
  - Use-Case-Diagramm erstellen **√**
- _Tests_:
  - Alle Funktionen testen und sehen, ob die Nachrichten korrekt dargestellt werden **√**
  - User anlegen und sheen ob seine Startseite korrekt angezeigt wird **√**
  - Jeder Benutzer gelangt nach dem Einloggen auf eine separate Startseite. **√**

**Comment by kps85** [comment]
**DONE**
- _Frontend_
  - Es muss eine Startseite angelegt werden
  - Platz zur Anzeige von Nachrichten
- _Backend_
  - Einen View erstellen, der das Fronendtemplate mit dem Modelobject verbindet
  - Den View um entsprechende Funktionen zur Anzeige von Nachrichten erweitern
- _Tests_
  - Alle Funktionen testen und sehen, ob die Nachrichten korrekt dargestellt werden
  - User anlegen und sheen ob seine Startseite korrekt angezeigt wird
  - Jeder Benutzer gelangt nach dem Einloggen auf eine separate Startseite

**UPDATE**
- _Frontend_
  - "Es muss möglich sein, auf die Startseite selbst, auf die Profilseite, die Einstellungsseite und auf die Infoseite durch das Klicken auf die Widgets zu gelangen" entfernt, Part einer anderen Story

**Comment by kps85** [comment]
**DONE**:
- _Frontend_:
  - CSS für GUI Design
  - JS functions für weitere Funktionalität

**Comment by Tomelinho** [comment]
**DONE:**
- _Dokumentation:_
  - Funktionsweise aufschreiben
  - Datenobjekte notieren
  - Relevante Texte der Infoseite hinzufügen
  - Use-Case-Diagramm erstellen

**UPDATE:**
- _Dokumentation:_
  - "EER-Diagramm ggf. erweitern" entfernt
