### ISSUE TITLE
Daten eines Benutzers auf dessen Profilseite einsehen (Profilseite)

### ISSUE THREAD

**Issue by kps85** [kps85/PPSN#93]
**TASKS**:
- _Frontend_:
  - Es muss eine Profilseite angelegt werden **√**
  - Es muss einen Container geben, in dem die Daten des Benutzers angegeben werden **√**
  - Name des Benutzers, Benutzername, Stadt, Registriert seit, Nachricht senden und folgen müssen angezeigt werden **√**
  - Freies Feld unter dem Profil für die Nachrichten des Nutzers erstellen **√**
  - Platzhalter für Profilbild des Benutzers  **√**
  - CSS für GUI Design **√**
  - JS functions für weitere Funktionalität **√**
- _Backend_:
  - Es muss einen View geben, der das Frontendtemplate mit dem Modelobject verbindet **√**
  - Die Nachrichten des Benutzers müssen in seinem Profil angezeigt werden **√**
  - Die Daten des Benutzers müssen den entsprechenden Inputfeldern zugeordnet aus der Datenbank ausgelesen und eingetragen werden **√**
- _Dokumentation_:
  - Funktionsweise aufschreiben **√**
  - Datenobjekte notieren **√**
  - Relevante Texte der Infoseite hinzufügen **√**
  - Use-Case-Diagramm erstellen **√**
- _Tests_:
  - Alle Funktionen testen **√**
  - Nachrichten versenden und auf die korrekte Darstellung hin prüfen **√**
  - Nutzer adressieren **√**
  - Benutzer können die Profile anderer Benutzer einsehen. **√**

**Comment by liliabut** [comment]
**DONE**:
- _Frontend_:
  - Es muss eine Profilseite angelegt werden
  - Es muss einen Container geben, in dem die Daten des Benutzers angegeben werden
  - Name des Benutzers, Benutzername, Stadt, Registriert seit, [Nachricht senden und folgen] müssen angezeigt werden
  - Freies Feld unter dem Profil für die Nachrichten des Nutzers erstellen
  - Platzhalter für Profilbild des Benutzers
  - CSS für GUI Design
  - JS functions für weitere Funktionalität
- _Backend_:
  - Es muss einen View geben, der das Frontendtemplate mit dem Modelobject verbindet
  - Die Nachrichten des Benutzers müssen in seinem Profil angezeigt werden
  - Die Daten des Benutzers müssen den entsprechenden Inputfeldern zugeordnet aus der Datenbank ausgelesen und eingetragen werden
- _Tests_:
  - Alle Funktionen testen
  - Nachrichten versenden und auf die korrekte Darstellung hin prüfen
  - Nutzer adressieren
  - Benutzer können die Profile anderer Benutzer einsehen.

**Comment by kps85** [comment]
**UPDATE**:
- _Tests_:
  - "Nutzer folgen" entfernt, Part eines anderen Sprints
  - "Nutzer über Profil anschreiben" entfernt, Part eines anderen Sprints

**Comment by Tomelinho** [comment]
**DONE:**
- _Dokumentation:_
  - Funktionsweise aufschreiben
  - Datenobjekte notieren
  - Relevante Texte der Infoseite hinzufügen
  - Use-Case-Diagramm erstellen

**UPDATE:**
- _Dokumentation:_
  - "EER-Diagramm ggf. erweitern" entfernt
