### ISSUE TITLE
Daten auf Seite verwalten / verändern (Einstellungsseite)

### ISSUE THREAD

**Issue by kps85** [kps85/PPSN#94]
**TASKS**:
- _Frontend_:
  - template für view erstellen (settings) **√**
  - input fields für username, password, email,  vorname, nachname, studiengang, matrikel-nummer, wohnort **√**
  - submit, reset button **√**
  - CSS für GUI Design **√**
  - JS functions für weitere Funktionalität **√**
- _Backend_:
  - entsprechende View ggf. erstellen **√**
  - entsprechende Views um notwendige Elemente erweitern **√**
  - Funktionen zum Updaten des Users in der DB implementieren **√**
  - ggf. Error-Handling **√**
- _Dokumentation_:
  - Funktionsweise aufschreiben **√**
  - Datenobjekte notieren **√**
  - relevante Texte der Infoseite hinzufügen **√**
  - Use-Case-Diagramm erstellen **√**
- _Tests_:
  - Testuser anlegen, alle Daten ändern und Änderungen in der Datenbank kontrollieren **√**
  - Daten zurücksetzen testen **√**
  - Eingaberestriktionen testen **√**
  - Benutzer können auf der Einstellungsseite ihre Daten verändern. **√**

**Comment by kps85** [comment]
**DONE**:
- _Frontend_:
  - template für view erstellen (settings)
  - input fields für username, password, email,  vorname, nachname, studiengang, matrikel-nummer, wohnort
  - submit, reset button
  - CSS für GUI Design
  - JS functions für weitere Funktionalität
- _Backend_:
  - entsprechende View ggf. erstellen
  - entsprechende Views um notwendige Elemente erweitern
  - Funktionen zum Updaten des Users in der DB implementieren
  - ggf. Error-Handling
- _Tests_:
  - Daten zurücksetzen testen
  - Eingaberestriktionen testen

**Comment by kps85** [comment]
**DONE**:
- _Tests_:
  - Testuser anlegen, alle Daten ändern und Änderungen in der Datenbank kontrollieren
  - Benutzer können auf der Einstellungsseite ihre Daten verändern.

**Comment by Tomelinho** [comment]
**DONE:**
- _Dokumentation:_
  - Funktionsweise aufschreiben
  - Datenobjekte notieren
  - relevante Texte der Infoseite hinzufügen
  - Use-Case-Diagramm erstellen

**UPDATE:**
- _Dokumentation:_
  - "EER-Diagramm ggf. erweitern" entfernt, weil es nicht benötigt wird
