### ISSUE TITLE
relevante Informationen zur Seite separiert einsehen (Infoseite)

### ISSUE THREAD

**Issue by kps85** [kps85/PPSN#95]
**TASKS**:
- _Frontend_:
  - template erstellen **√**
  - FAQs, Impressum, Über Uns hinzufügen **√**
  - widgets zur Navigation hinzufügen **√**
  - CSS für GUI design **√**
  - JS functions für weitere Funktionalität **√**
- _Backend_:
  - entsprechende View ggf. erstellen **√**
  - entsprechende Views um notwendige Elemente erweitern **√**
- _Dokumentation_:
  - Funktionsweise aufschreiben **√**
  - Datenobjekte notieren **√**
  - relevante Texte der Infoseite hinzufügen **√**
  - Use-Case-Diagramm erstellen **√**
- _Tests_:
  - Infoseite aufrufen **√**
  - innerhalb der Infoseite durch FAQs und andere Informationen navigieren **√**
  - Es existiert eine Infoseite. **√**

**Comment by kps85** [comment]
**DONE**:
- _Frontend_:
  - template erstellen
  - FAQs, Impressum, Über Uns hinzufügen
  - widgets zur Navigation hinzufügen
  - CSS für GUI design
  - JS functions für weitere Funktionalität
- _Backend_:
  - entsprechende View ggf. erstellen
  - entsprechende Views um notwendige Elemente erweitern
- _Tests_:
  - Infoseite aufrufen
  - innerhalb der Infoseite durch FAQs und andere Informationen navigieren
  - Es existiert eine Infoseite.

**Comment by Tomelinho** [comment]
**DONE:**
- _Dokumentation:_
  - Funktionsweise aufschreiben
  - Datenobjekte notieren
  - relevante Texte der Infoseite hinzufügen
  - Use-Case-Diagramm erstellen

**Comment by Tomelinho** [comment]
**UPDATE:**
- _Dokumentation:_
  - "EER-Diagramm ggf. erweitern" entfernt, da es nicht notwendig ist
