### ISSUE TITLE
Hilfefunktionen bezüglich der Seite zugreifen (Infoseite)

### ISSUE THREAD

**Issue by kps85** [kps85/PPSN#96]
**TASKS**:
- _Frontend_:
  - Supportformulare erstellen **√**
  - inputs für betreff, kategorie, anfrage hinzufügen **√**
  - widget zur Auswahl der Anfrage hinzufügen **√**
  - Kontaktdaten des Teams hinzufügen **√**
  - CSS für GUI design **√**
  - JS functions für weitere Funktionalität **√**
- _Backend_:
  - entsprechende Views um notwendige Elemente erweitern **√**
- _Dokumentation_:
  - Funktionsweise aufschreiben **√**
  - Datenobjekte notieren **√**
  - relevante Texte der Infoseite hinzufügen **√**
  - Use-Case-Diagramm erstellen **√**
- _Tests_:
  - Infoseite aufrufen und durch Hilfefunktionen navigieren **√**
  - Es existiert eine Infoseite mit Hilfefunktionen. **√**

**Comment by kps85** [comment]
**DONE**:
- _Frontend_:
  - Supportformulare erstellen
  - inputs für betreff, kategorie, anfrage hinzufügen
  - widget zur Auswahl der Anfrage hinzufügen
  - Kontaktdaten des Teams hinzufügen
  - CSS für GUI design
  - JS functions für weitere Funktionalität
- _Backend_:
  - entsprechende Views um notwendige Elemente erweitern
- _Tests_:
  - Infoseite aufrufen und durch Hilfefunktionen navigieren
  - Es existiert eine Infoseite mit Hilfefunktionen.

**Comment by kps85** [comment]
**UPDATE**:
- _Backend_:
  - "Funktionen zum Absenden einer Supportanfrage implementieren" entfernt, Part eines anderen Sprints
- _Tests_:
  - "Supportanfrage absenden und auf Eingang prüfen" entfernt, Part eines anderen Sprints

**Comment by Tomelinho** [comment]
**DONE:**
- _Dokumentation_:
  - Funktionsweise aufschreiben
  - Datenobjekte notieren
  - Use-Case-Diagramm erstellen
  - relevante Texte der Infoseite hinzufügen

**Comment by Tomelinho** [comment]
**UPDATE:**
- _Dokumentation:_
  - "EER-Diagramm ggf. erweitern" entfernt, da es nicht notwendig ist
